name: deploy project to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'


      - name: Setup deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run deploy script
        run: deno run --allow-write=dist --allow-run --no-prompt ./deploy.ts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist